# Generated by Django 6.0.2 on 2026-02-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.URLField(max_length=300, verbose_name='URL постера')),
                ('trailer', models.URLField(blank=True, max_length=300, null=True, verbose_name='URL трейлера')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('duration', models.IntegerField(verbose_name='Длительность (мин)')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
