# Generated by Django 6.0.2 on 2026-04-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
